#page title
page_title                                : Fallout FISSION                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

head_icon                                 : assets/fallout-fission-logo.jpg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_icon                                  : assets/Fission_Mac_Icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Fallout FISSION                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Split from the past, powering the future.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cambragol                              
your_link                                 : https://github.com/cambragol                   
your_city                                 : the Wasteland                                
email_address                             : cambragol@protonmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : cambragol
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Fallout 2 Widescreen
    description                           : The original game, but fine-tuned for modern, widescreen monitors.
    fontawesome_icon_name                 : magic
    
  - title                                 : Mulit-platform
    description                           : Works on macOS, Windows, Linus, and maybe even your phone!
    fontawesome_icon_name                 : mobile

  - title                                 : Pixel Perfect
    description                           : Play it your way, stretched, original, aspect ratio, square pixels, or high quality.
    fontawesome_icon_name                 : play-circle

  - title                                 : Extended Pipboy
    description                           : The pipboy menus are expanded to handle data of any size, and accept keyboard input.
    fontawesome_icon_name                 : sync

  - title                                 : Drop in Ready
    description                           : Drop the app into your Fallout 2 or TC install and you are ready to go!
    fontawesome_icon_name                 : adjust
  
  - title                                 : Mod Ready
    description                           : Ready for mods to be created and added, and coexist without interminable configuration.
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Screenshot List                         Edit, add or remove screenshots to be presented.
screenshots                               :

  - title                                 : Full Screen Video
    description                           : Videos can be stretched to full screen, maintain aspect ratio, or with square pixels.
    fontawesome_icon_name                 : magic
    image                                 : assets/screenshot1.png
    thumb                                 : assets/screenshot1_thumb.png
    
  - title                                 : Enhanced Preferences
    description                           : Change all the critical settings from within the game in the enhanced preferences screen.
    fontawesome_icon_name                 : mobile
    image                                 : assets/screenshot2.png
    thumb                                 : assets/screenshot2_thumb.png

  - title                                 : Widescreen Character Selection
    description                           : Customized widescreen character graphics
    fontawesome_icon_name                 : play-circle
    image                                 : assets/screenshot3.png
    thumb                                 : assets/screenshot3_thumb.png

  - title                                 : Widescreen Character Editor
    description                           : Customized offsets for all interfaces in widescreen.
    fontawesome_icon_name                 : magic
    image                                 : assets/screenshot4.png
    thumb                                 : assets/screenshot4_thumb.png
    
  - title                                 : Customized Splash Screens
    description                           : All splash screens customized for wide screens.
    fontawesome_icon_name                 : mobile
    image                                 : assets/screenshot5.png
    thumb                                 : assets/screenshot5_thumb.png

  - title                                 : Customized Load Screens
    description                           : Widescreen load/save screens with expanded slots.
    fontawesome_icon_name                 : play-circle
    image                                 : assets/screenshot6.png
    thumb                                 : assets/screenshot6_thumb.png

  - title                                 : Widescreen Worldmap
    description                           : World map and town screens are supported in widescreen
    fontawesome_icon_name                 : magic
    image                                 : assets/screenshot7.png
    thumb                                 : assets/screenshot7_thumb.png
    
  - title                                 : Large Play Area
    description                           : Play area can be set to original, default, large or huge.
    fontawesome_icon_name                 : mobile
    image                                 : assets/screenshot8.png
    thumb                                 : assets/screenshot8_thumb.png

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
