#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

head_icon                                 : assets/fallout-fission-logo.jpg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_icon                                  : assets/Fission_Mac_Icon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Fallout FISSION                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Split from the past, powering the future.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Cambragol                              
your_link                                 : https://github.com/cambragol                   
your_city                                 : Wasteland                                
email_address                             : cambragol@protonmail.com
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : cambragol
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : GitHub Pages Jekyll Theme
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voil치!
    fontawesome_icon_name                 : magic
    
  - title                                 : iPhone Device Preview
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : mobile

  - title                                 : Video Support
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : play-circle

  - title                                 : Automatic Icon and Metadata
    description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : adjust
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : Smart App Banner
    description                           : Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Social Links
    description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : link

  - title                                 : FontAwesome Support
    description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Screenshot List                         Edit, add or remove screenshots to be presented.
screenshots                               :

  - title                                 : GitHub Pages Jekyll Theme
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voil치!
    fontawesome_icon_name                 : magic
    image                                 : assets/screenshot1.png
    thumb                                 : assets/screenshot1_thumb.png
    
  - title                                 : iPhone Device Preview
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : mobile
    image                                 : assets/screenshot2.png
    thumb                                 : assets/screenshot2_thumb.png

  - title                                 : Video Support
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : play-circle
    image                                 : assets/screenshot3.png
    thumb                                 : assets/screenshot3_thumb.png

  - title                                 : Screenshot 4
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voil치!
    fontawesome_icon_name                 : magic
    image                                 : assets/screenshot4.png
    thumb                                 : assets/screenshot4_thumb.png
    
  - title                                 : Screenshot 5
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : mobile
    image                                 : assets/screenshot5.png
    thumb                                 : assets/screenshot5_thumb.png

  - title                                 : Screenshot 6
    description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
    fontawesome_icon_name                 : play-circle
    image                                 : assets/screenshot6.png
    thumb                                 : assets/screenshot6_thumb.png

  - title                                 : Screenshot 7
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voil치!
    fontawesome_icon_name                 : magic
    image                                 : assets/screenshot7.png
    thumb                                 : assets/screenshot7_thumb.png
    
  - title                                 : Screenshot 8
    description                           : Preview your app in the context of an iPhone device. Five different device colors included.
    fontawesome_icon_name                 : mobile
    image                                 : assets/screenshot8.png
    thumb                                 : assets/screenshot8_thumb.png

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
